// <auto-generated />
using System;
using GIGANTECORE.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GIGANTECORE.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241123235228_HistorialCorreo-DetalleSolicitud")]
    partial class HistorialCorreoDetalleSolicitud
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GIGANTECORE.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Administrador");

                    b.Property<bool?>("SoloLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Admin__3214EC07A4E8858C");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("GIGANTECORE.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Carrito__3214EC0784CC7F99");

                    b.HasIndex(new[] { "ProductoId" }, "IX_Carrito_ProductoId");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_Carrito_UsuarioId");

                    b.ToTable("Carrito", (string)null);
                });

            modelBuilder.Entity("GIGANTECORE.Models.Categorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07791AF110");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Compañium", b =>
                {
                    b.Property<string>("Rnc")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("RNC");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Rnc")
                        .HasName("PK__Compañia__CAFF6951C669784F");

                    b.ToTable("Compañia");
                });

            modelBuilder.Entity("GIGANTECORE.Models.DetalleSolicitud", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle")
                        .HasName("PK__DetalleS__E43646A58EBFD1A7");

                    b.HasIndex(new[] { "IdSolicitud" }, "IX_DetalleSolicitud_IdSolicitud");

                    b.HasIndex(new[] { "ProductoId" }, "IX_DetalleSolicitud_ProductoId");

                    b.ToTable("DetalleSolicitud", (string)null);
                });

            modelBuilder.Entity("GIGANTECORE.Models.HistorialCorreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DetalleSolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Enviado");

                    b.Property<DateTime?>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Historia__3214EC0765966D64");

                    b.HasIndex(new[] { "DetalleSolicitudId" }, "IX_HistorialCorreo_DetalleSolicitudId");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_HistorialCorreo_UsuarioId");

                    b.ToTable("HistorialCorreo", (string)null);
                });

            modelBuilder.Entity("GIGANTECORE.Models.Producto", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SubCategoriaId")
                        .HasColumnType("int");

                    b.HasKey("Codigo")
                        .HasName("PK__tmp_ms_x__06370DAD53EE836F");

                    b.HasIndex(new[] { "CategoriaId" }, "IX_Productos_CategoriaId");

                    b.HasIndex(new[] { "SubCategoriaId" }, "IX_Productos_SubCategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GIGANTECORE.Models.RolePermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRead")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("RolePermisos");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<DateTime?>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitud")
                        .HasName("PK__Solicitu__36899CEF05DB70D6");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_Solicitud_UsuarioId");

                    b.ToTable("Solicitud", (string)null);
                });

            modelBuilder.Entity("GIGANTECORE.Models.SubCategorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__SubCateg__3214EC079C3939DB");

                    b.HasIndex(new[] { "CategoriaId" }, "IX_SubCategoria_CategoriaId");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("GIGANTECORE.Models.UsuarioCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Rnc")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("RNC");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__UsuarioC__3214EC07D79F99F6");

                    b.HasIndex(new[] { "Rnc" }, "IX_UsuarioCliente_RNC");

                    b.ToTable("UsuarioCliente", (string)null);
                });

            modelBuilder.Entity("GIGANTECORE.Models.Carrito", b =>
                {
                    b.HasOne("GIGANTECORE.Models.Producto", "Producto")
                        .WithMany("Carritos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Carrito__Product__6C190EBB");

                    b.HasOne("GIGANTECORE.Models.UsuarioCliente", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Carrito__Usuario__46E78A0C");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GIGANTECORE.Models.DetalleSolicitud", b =>
                {
                    b.HasOne("GIGANTECORE.Models.Solicitud", "IdSolicitudNavigation")
                        .WithMany("DetalleSolicituds")
                        .HasForeignKey("IdSolicitud")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleSo__IdSol__4D94879B");

                    b.HasOne("GIGANTECORE.Models.Producto", "Producto")
                        .WithMany("DetalleSolicituds")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleSo__Produ__6D0D32F4");

                    b.Navigation("IdSolicitudNavigation");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GIGANTECORE.Models.HistorialCorreo", b =>
                {
                    b.HasOne("GIGANTECORE.Models.DetalleSolicitud", "DetalleSolicitud")
                        .WithMany("HistorialCorreos")
                        .HasForeignKey("DetalleSolicitudId")
                        .IsRequired()
                        .HasConstraintName("FK__HistorialCorreo__DetalleSolicitudId");

                    b.HasOne("GIGANTECORE.Models.UsuarioCliente", "Usuario")
                        .WithMany("HistorialCorreos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__HistorialCorreo__UsuarioId");

                    b.Navigation("DetalleSolicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Producto", b =>
                {
                    b.HasOne("GIGANTECORE.Models.Categorium", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK_Productos_Categoria");

                    b.HasOne("GIGANTECORE.Models.SubCategorium", "SubCategoria")
                        .WithMany("Productos")
                        .HasForeignKey("SubCategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__SubCa__6EF57B66");

                    b.Navigation("Categoria");

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Solicitud", b =>
                {
                    b.HasOne("GIGANTECORE.Models.UsuarioCliente", "Usuario")
                        .WithMany("Solicituds")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Solicitud__Usuar__4AB81AF0");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GIGANTECORE.Models.SubCategorium", b =>
                {
                    b.HasOne("GIGANTECORE.Models.Categorium", "Categoria")
                        .WithMany("SubCategoria")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__SubCatego__Categ__3F466844");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GIGANTECORE.Models.UsuarioCliente", b =>
                {
                    b.HasOne("GIGANTECORE.Models.Compañium", "RncNavigation")
                        .WithMany("UsuarioClientes")
                        .HasForeignKey("Rnc")
                        .HasConstraintName("FK_UsuarioCliente_Compañia");

                    b.Navigation("RncNavigation");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Categorium", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Compañium", b =>
                {
                    b.Navigation("UsuarioClientes");
                });

            modelBuilder.Entity("GIGANTECORE.Models.DetalleSolicitud", b =>
                {
                    b.Navigation("HistorialCorreos");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Producto", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("DetalleSolicituds");
                });

            modelBuilder.Entity("GIGANTECORE.Models.Solicitud", b =>
                {
                    b.Navigation("DetalleSolicituds");
                });

            modelBuilder.Entity("GIGANTECORE.Models.SubCategorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GIGANTECORE.Models.UsuarioCliente", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("HistorialCorreos");

                    b.Navigation("Solicituds");
                });
#pragma warning restore 612, 618
        }
    }
}
